export const colorData = [
    {
        step: 0,
        row: 2,
        column: 2,
        mainColor: "#49d7d9",
        pickColor: "#88dddf",
        pickId: 1,
    },
    {
        step: 1,
        row: 2,
        column: 2,
        mainColor: "#ba3a13",
        pickColor: "#ba3a31",
        pickId: 3,
    },
    {
        step: 2,
        row: 2,
        column: 2,
        mainColor: "#534a43",
        pickColor: "#534a4b",
        pickId: 2,
    },
    {
        step: 3,
        row: 2,
        column: 2,
        mainColor: "#516d57",
        pickColor: "#5f6d57",
        pickId: 1,
    },
    {
        step: 4,
        row: 2,
        column: 2,
        mainColor: "#39b35e",
        pickColor: "#64b35e",
        pickId: 1,
    },
    {
        step: 5,
        row: 2,
        column: 2,
        mainColor: "#333a92",
        pickColor: "#333a83",
        pickId: 3,
    },
    {
        step: 6,
        row: 3,
        column: 3,
        mainColor: "#53672a",
        pickColor: "#5e702c",
        pickId: 1,
    },
    {
        step: 7,
        row: 3,
        column: 3,
        mainColor: "#f84c48",
        pickColor: "#e44248",
        pickId: 0,
    },
    {
        step: 8,
        row: 3,
        column: 3,
        mainColor: "#ea9b63",
        pickColor: "#ea9b50",
        pickId: 0,
    },
    {
        step: 9,
        row: 3,
        column: 3,
        mainColor: "#53f92b",
        pickColor: "#81ef5b",
        pickId: 3,
    },
    {
        step: 10,
        row: 3,
        column: 3,
        mainColor: "#d9bbf9",
        pickColor: "#d6c0de",
        pickId: 6,
    },
    {
        step: 11,
        row: 3,
        column: 3,
        mainColor: "#84e4b4",
        pickColor: "#9ff1c8",
        pickId: 5,
    },
    {
        step: 12,
        row: 3,
        column: 3,
        mainColor: "#ae83f7",
        pickColor: "#9874d3",
        pickId: 7,
    },
    {
        step: 13,
        row: 4,
        column: 4,
        mainColor: "#e99ec9",
        pickColor: "#fcb4dd",
        pickId: 10,
    },
    {
        step: 14,
        row: 4,
        column: 4,
        mainColor: "#32881d",
        pickColor: "#3a7e29",
        pickId: 6,
    },
    {
        step: 15,
        row: 4,
        column: 4,
        mainColor: "#9ec924",
        pickColor: "#b3d74e",
        pickId: 10,
    },
    {
        step: 16,
        row: 4,
        column: 4,
        mainColor: "#99fbfe",
        pickColor: "#b3f7f9",
        pickId: 4,
    },
    {
        step: 17,
        row: 4,
        column: 4,
        mainColor: "#89bbd6",
        pickColor: "#75aac7",
        pickId: 4,
    },
    {
        step: 18,
        row: 5,
        column: 5,
        mainColor: "#476a49",
        pickColor: "#466047",
        pickId: 20,
    },
    {
        step: 19,
        row: 5,
        column: 5,
        mainColor: "#6dd6f6",
        pickColor: "#a1e5fa",
        pickId: 6,
    },
    {
        step: 20,
        row: 5,
        column: 5,
        mainColor: "#57e95a",
        pickColor: "#91f894",
        pickId: 15,
    },
    {
        step: 21,
        row: 5,
        column: 5,
        mainColor: "#9704ad",
        pickColor: "#832e8f",
        pickId: 23,
    },
    {
        step: 22,
        row: 6,
        column: 6,
        mainColor: "#087e32",
        pickColor: "#1f6d3b",
        pickId: 10,
    },
    {
        step: 23,
        row: 6,
        column: 6,
        mainColor: "#95f748",
        pickColor: "#7be527",
        pickId: 23,
    },
    {
        step: 24,
        row: 6,
        column: 6,
        mainColor: "#e72a30",
        pickColor: "#c01f24",
        pickId: 20,
    },
    {
        step: 25,
        row: 6,
        column: 6,
        mainColor: "#c79f7b",
        pickColor: "#cba787",
        pickId: 20,
    },
    {
        step: 26,
        row: 6,
        column: 6,
        mainColor: "#b75063",
        pickColor: "#a64c5d",
        pickId: 5,
    },
    {
        step: 27,
        row: 6,
        column: 6,
        mainColor: "#4b4e23",
        pickColor: "#484b1d",
        pickId: 12,
    },
    {
        step: 28,
        row: 6,
        column: 6,
        mainColor: "#646bb1",
        pickColor: "#6a71b8",
        pickId: 10,
    },
    {
        step: 29,
        row: 6,
        column: 6,
        mainColor: "#a5949a",
        pickColor: "#bba4ac",
        pickId: 20,
    },
    {
        step: 30,
        row: 6,
        column: 6,
        mainColor: "#ed8429",
        pickColor: "#f0913e",
        pickId: 23,
    },
    {
        step: 31,
        row: 6,
        column: 6,
        mainColor: "#770d7c",
        pickColor: "#6e0573",
        pickId: 14,
    },
    {
        step: 32,
        row: 6,
        column: 6,
        mainColor: "#de7c25",
        pickColor: "#f6943d",
        pickId: 4,
    },
    {
        step: 33,
        row: 6,
        column: 6,
        mainColor: "#840d33",
        pickColor: "#941d43",
        pickId: 33,
    },
    {
        step: 34,
        row: 6,
        column: 6,
        mainColor: "#f9ca86",
        pickColor: "#ffd996",
        pickId: 15,
    },
]